"""Add note to Order

Revision ID: 29babd2d2edc
Revises: c67c57770d96
Create Date: 2025-03-16 16:54:43.677088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29babd2d2edc'
down_revision = 'c67c57770d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
