"""add_discount_fields

Revision ID: 2e371d83c60a
Revises: 29babd2d2edc
Create Date: 2025-03-31 15:05:56.843955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e371d83c60a'
down_revision = '29babd2d2edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_column('valid_until')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('discount_code')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discount_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('discount_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
