"""Add nullable address fields to Order

Revision ID: 49d0da63db0e
Revises: 9f44fc275047
Create Date: 2025-03-13 02:10:39.248723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d0da63db0e'
down_revision = '9f44fc275047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('billing_address')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
