"""Add price_per_item to OrderItem

Revision ID: a5ab07f239e6
Revises: 4eae3ebc6d0d
Create Date: 2025-03-12 15:55:35.650520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ab07f239e6'
down_revision = '4eae3ebc6d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_item', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('price_per_item')

    # ### end Alembic commands ###
