"""Add visible_to_user flag to Order

Revision ID: bacbbcdc690b
Revises: 2e371d83c60a
Create Date: 2025-03-31 19:12:02.262481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacbbcdc690b'
down_revision = '2e371d83c60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('visible_to_user')

    # ### end Alembic commands ###
